### ISSUE TITLE
Unable to upload pact files to broker server

### ISSUE THREAD

**Issue by rashmi23456** [warmuuh/pactbroker-maven-plugin#14]
**When using the maven plugin to upload pact files, it is throwing the below error:**

[INFO] --- pactbroker-maven-plugin:0.0.9:upload-pacts (upload-pacts) @ micro-service-1 ---

[INFO] loading pacts from /Users/rashmi.patil/workspace/prod-engg/test-pact/pact/pact-junit-java/micro-service-1/target/pacts

[INFO] found pact file: Service1-Service2.json

[INFO] Uploading pact to http://localhost:8080/pacts/provider/Service2/consumer/Service1/version/1.0.0

[INFO] ------------------------------------------------------------------------

[INFO] BUILD FAILURE

[INFO] ------------------------------------------------------------------------

[INFO] Total time: 12.814 s

[INFO] Finished at: 2016-09-26T13:58:40+05:30

[INFO] Final Memory: 21M/292M

[INFO] ------------------------------------------------------------------------

[ERROR] Failed to execute goal com.github.warmuuh:pactbroker-maven-plugin:0.0.9:upload-pacts (upload-pacts) on project micro-service-1: Failed to read pacts: Connection refused -> [Help 1]

**Comment by warmuuh** [comment]
then apparently the server was not running...
