### ISSUE TITLE
Release 0.0.11

### ISSUE THREAD

**Issue by BenSayers** [warmuuh/pactbroker-maven-plugin#20]
Thanks for merging https://github.com/warmuuh/pactbroker-maven-plugin/pull/19

Please release these changes in next version of the plugin so we can start using them.

**Comment by warmuuh** [comment]
Released 0.0.11.  you can always use master-SNAPSHOT to get the latest version though.

**Comment by BenSayers** [comment]
Ah ok I didn't know that. Although some of our teams would not be comfortable automatically pulling in the latest version. Thanks for the release!
