### ISSUE TITLE
Authentication is required but no CredentialsProvider has been registered

### ISSUE THREAD

**Issue by bankras** [warmuuh/pactbroker-maven-plugin#4]
When trying to use a git repository to store the pact files, the plugin fails with message
`Authentication is required but no CredentialsProvider has been registered`

As of yet I have been unable to determine a way to register any credentials.

**Comment by ghost** [comment]
If you use JGit, you shoud then you connect to remote repository:
Collection<Ref> refs = Git.lsRemoteRepository()
                .setCredentialsProvider(userProvider)
                .setRemote(remoteURL)
                .call();
Use method - setCredentialsProvider, variable userProvider - UsernamePasswordCredentialsProvider, http://download.eclipse.org/jgit/site/4.2.0.201601211800-r/apidocs/org/eclipse/jgit/transport/UsernamePasswordCredentialsProvider.html
