### ISSUE TITLE
Release of 0.0.5

### ISSUE THREAD

**Issue by scho** [warmuuh/pactbroker-maven-plugin#5]
Hey there,

would you mind, releasing a new version? We are relying on the changes from the PRs. Currently, we use the snapshot version deployed to our company nexus instance.

Thanks for your help!

Cheers
Georg

**Comment by warmuuh** [comment]
Done.  Sorry for that delay. It might be a better idea to maybe fork and use jitpack.io on your fork, than you are in control. and also this repo is not under active development.

**Comment by warmuuh** [comment]
And thank you by the way for your work on this. I appreciate this
